"""Generator for AxISA's rtl/soc_top.v (3D XYZ NoC mesh). Re-derived from
router.v, noc_core_adapter.v, and noc_mem_adapter.v's actual port
semantics - not a hand-authored file, since one router+adapter pair
instantiation is repeated (with different coordinates) once per grid
position, and hand-editing this file directly is how a mesh-scale-up
mistake gets made silently. To scale the mesh: run this with new
X/Y/Z sizes, regenerate tb/tb_soc.v with tools/gen_tb_soc.py at the
same size, then compile - no other files need to change.

Usage: python gen_soc_top.py <X> <Y> <Z> <out_path>
       (defaults to 12 12 24 rtl/soc_top.v with no arguments)

Direction/axis mapping: E=+X, W=-X, S=+Y, N=-Y, D=+Z, U=-Z. Ana/Kata
(the 4th axis, W in router.v's own naming - unrelated to this file's
X/Y/Z/W size variables) are always tied off/unused - this mesh has no
4th spatial axis.

Core indexing: nested loop x outer, y middle, z inner, sequential
index SKIPS the one grid position reserved for memory (memory itself
never gets a core index) - confirmed against the mesh's own ASCII
grid-layout convention (see any generated file's header comment).

Memory sits at the lower of the two symmetric center positions on
every axis (never a corner) - the established placement convention
for every mesh size this project has used.
"""
import sys

if len(sys.argv) >= 5:
    X_SIZE, Y_SIZE, Z_SIZE = int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3])
    OUT_PATH = sys.argv[4]
else:
    X_SIZE, Y_SIZE, Z_SIZE = 12, 12, 24
    OUT_PATH = "rtl/soc_top.v"
COORD_BITS = max(4, (max(X_SIZE, Y_SIZE, Z_SIZE) - 1).bit_length())
REQ_FW = 8 * COORD_BITS + 68
RESP_FW = 4 * COORD_BITS + 32
MEM_X, MEM_Y, MEM_Z = X_SIZE // 2 - 1, Y_SIZE // 2 - 1, Z_SIZE // 2 - 1

OPP = {'E': 'W', 'W': 'E', 'S': 'N', 'N': 'S', 'D': 'U', 'U': 'D'}
NEIGHBOR = {
    'E': (1, 0, 0), 'W': (-1, 0, 0),
    'S': (0, 1, 0), 'N': (0, -1, 0),
    'D': (0, 0, 1), 'U': (0, 0, -1),
}


def in_bounds(x, y, z):
    return 0 <= x < X_SIZE and 0 <= y < Y_SIZE and 0 <= z < Z_SIZE


def all_positions():
    for x in range(X_SIZE):
        for y in range(Y_SIZE):
            for z in range(Z_SIZE):
                yield (x, y, z)


def build_core_index_map():
    idx = 0
    coord_to_idx = {}
    idx_to_coord = {}
    for (x, y, z) in all_positions():
        if (x, y, z) == (MEM_X, MEM_Y, MEM_Z):
            continue
        coord_to_idx[(x, y, z)] = idx
        idx_to_coord[idx] = (x, y, z)
        idx += 1
    return coord_to_idx, idx_to_coord


def main():
    coord_to_idx, idx_to_coord = build_core_index_map()
    n_cores = len(coord_to_idx)

    lines = []
    w = lines.append

    w(f"// AxISA's NoC mini-SoC - a real 3D {X_SIZE}x{Y_SIZE}x{Z_SIZE} mesh")
    w(f"// ({n_cores} cores + 1 memory). Generated by tools/gen_soc_top.py -")
    w("// do not hand-edit; re-run the generator with new sizes instead.")
    w(f"// Memory lives at ({MEM_X},{MEM_Y},{MEM_Z}).")
    w("`timescale 1ns/1ps")
    w("")
    w("module soc_top #(")
    for i in range(n_cores):
        w(f'    parameter C{i}_INSTR_HEX = "",')
    w("    parameter INSTR_MEM_WORDS  = 1024,")
    w("    parameter DATA_MEM_WORDS   = 1024,")
    w("    parameter SHARED_MEM_BASE  = 32'h0000_2000,")
    w("    parameter SHARED_MEM_BYTES = 256")
    w(") (")
    w("    input  wire        clk,")
    w("    input  wire        reset,")
    for i in range(n_cores):
        w(f"    output wire        c{i}_halted,")
        w(f"    output wire [31:0]  c{i}_tohost,")
    w("    output wire        all_halted")
    w(");")
    w("")

    # ---- Link wire declarations ----
    w("    // ==================== Mesh link wires ====================")
    for (x, y, z) in all_positions():
        for d, (dx, dy, dz) in NEIGHBOR.items():
            nx, ny, nz = x + dx, y + dy, z + dz
            if in_bounds(nx, ny, nz):
                w(f"    wire req_{x}_{y}_{z}_{d}_v, req_{x}_{y}_{z}_{d}_r; wire [{REQ_FW-1}:0] req_{x}_{y}_{z}_{d}_f;")
                w(f"    wire resp_{x}_{y}_{z}_{d}_v, resp_{x}_{y}_{z}_{d}_r; wire [{RESP_FW-1}:0] resp_{x}_{y}_{z}_{d}_f;")
    w("")

    # ---- Per-core bus/adapter wires ----
    w("    // ==================== Per-core bus/adapter wires ====================")
    for i in range(n_cores):
        w(f"    wire c{i}_bus_req, c{i}_bus_mem_write, c{i}_bus_mem_unsigned, c{i}_bus_grant;")
        w(f"    wire [31:0] c{i}_bus_addr, c{i}_bus_write_data, c{i}_bus_read_data;")
        w(f"    wire [1:0] c{i}_bus_mem_size;")
        w(f"    wire c{i}_req_out_valid, c{i}_req_out_ready, c{i}_resp_in_valid, c{i}_resp_in_ready;")
        w(f"    wire [{REQ_FW-1}:0] c{i}_req_out_flit;")
        w(f"    wire [{RESP_FW-1}:0] c{i}_resp_in_flit;")
    w("")
    w("    wire mem_req_in_valid, mem_req_in_ready, mem_resp_out_valid, mem_resp_out_ready;")
    w(f"    wire [{REQ_FW-1}:0] mem_req_in_flit;")
    w(f"    wire [{RESP_FW-1}:0] mem_resp_out_flit;")
    w("")

    # ---- Router instantiations ----
    w("    // ==================== Routers ====================")
    for (x, y, z) in all_positions():
        is_mem = (x, y, z) == (MEM_X, MEM_Y, MEM_Z)
        core_i = coord_to_idx.get((x, y, z))

        for net, fw in (("req", REQ_FW), ("resp", RESP_FW)):
            w(f"    router #(.FLIT_WIDTH({fw}), .COORD_BITS({COORD_BITS}), .MY_X({x}), .MY_Y({y}), .MY_Z({z}), .MY_W(0)) {net}_r{x}_{y}_{z} (")
            w("        .clk(clk), .reset(reset),")
            for d, port in (('N', 'n'), ('E', 'e'), ('S', 's'), ('W', 'w'), ('U', 'u'), ('D', 'd')):
                dx, dy, dz = NEIGHBOR[d]
                nx, ny, nz = x + dx, y + dy, z + dz
                if in_bounds(nx, ny, nz):
                    opp = OPP[d]
                    in_sig = f"{net}_{nx}_{ny}_{nz}_{opp}"
                    out_sig = f"{net}_{x}_{y}_{z}_{d}"
                    w(f"        .{port}_in_valid({in_sig}_v), .{port}_in_flit({in_sig}_f), .{port}_in_ready({in_sig}_r),")
                    w(f"        .{port}_out_valid({out_sig}_v), .{port}_out_flit({out_sig}_f), .{port}_out_ready({out_sig}_r),")
                else:
                    w(f"        .{port}_in_valid(1'b0), .{port}_in_flit({{{fw}{{1'b0}}}}), .{port}_in_ready(),")
                    w(f"        .{port}_out_valid(), .{port}_out_flit(), .{port}_out_ready(1'b0),")
            # Ana/Kata (4th axis W) - always unused at this mesh's size.
            w(f"        .ana_in_valid(1'b0), .ana_in_flit({{{fw}{{1'b0}}}}), .ana_in_ready(),")
            w("        .ana_out_valid(), .ana_out_flit(), .ana_out_ready(1'b0),")
            w(f"        .kata_in_valid(1'b0), .kata_in_flit({{{fw}{{1'b0}}}}), .kata_in_ready(),")
            w("        .kata_out_valid(), .kata_out_flit(), .kata_out_ready(1'b0),")
            # Local port
            if net == "req":
                if is_mem:
                    w("        .l_in_valid(1'b0), .l_in_flit({%d{1'b0}}), .l_in_ready()," % fw)
                    w("        .l_out_valid(mem_req_in_valid), .l_out_flit(mem_req_in_flit), .l_out_ready(mem_req_in_ready)")
                else:
                    w(f"        .l_in_valid(c{core_i}_req_out_valid), .l_in_flit(c{core_i}_req_out_flit), .l_in_ready(c{core_i}_req_out_ready),")
                    w("        .l_out_valid(), .l_out_flit(), .l_out_ready(1'b0)")
            else:
                if is_mem:
                    w("        .l_in_valid(mem_resp_out_valid), .l_in_flit(mem_resp_out_flit), .l_in_ready(mem_resp_out_ready),")
                    w("        .l_out_valid(), .l_out_flit(), .l_out_ready(1'b0)")
                else:
                    w("        .l_in_valid(1'b0), .l_in_flit({%d{1'b0}}), .l_in_ready()," % fw)
                    w(f"        .l_out_valid(c{core_i}_resp_in_valid), .l_out_flit(c{core_i}_resp_in_flit), .l_out_ready(c{core_i}_resp_in_ready)")
            w("    );")
            w("")

    # ---- Core instantiations ----
    w("    // ==================== Cores ====================")
    for i in range(n_cores):
        (x, y, z) = idx_to_coord[i]
        w(f"    cpu_core #(")
        w(f"        .INSTR_MEM_WORDS(INSTR_MEM_WORDS), .INSTR_INIT_FILE(C{i}_INSTR_HEX),")
        w(f"        .DATA_MEM_WORDS(DATA_MEM_WORDS),")
        w(f"        .SHARED_MEM_BASE(SHARED_MEM_BASE), .SHARED_MEM_BYTES(SHARED_MEM_BYTES)")
        w(f"    ) c{i}_core (")
        w(f"        .clk(clk), .reset(reset),")
        w(f"        .halted(c{i}_halted), .tohost_value(c{i}_tohost),")
        w(f"        .bus_req(c{i}_bus_req), .bus_addr(c{i}_bus_addr), .bus_write_data(c{i}_bus_write_data),")
        w(f"        .bus_mem_write(c{i}_bus_mem_write), .bus_mem_size(c{i}_bus_mem_size), .bus_mem_unsigned(c{i}_bus_mem_unsigned),")
        w(f"        .bus_grant(c{i}_bus_grant), .bus_read_data(c{i}_bus_read_data)")
        w(f"    );")
        w("")
        w(f"    noc_core_adapter #(")
        w(f"        .COORD_BITS({COORD_BITS}), .MY_X({x}), .MY_Y({y}), .MY_Z({z}), .MY_W(0),")
        w(f"        .MEM_X({MEM_X}), .MEM_Y({MEM_Y}), .MEM_Z({MEM_Z}), .MEM_W(0),")
        w(f"        .REQ_FLIT_WIDTH({REQ_FW}), .RESP_FLIT_WIDTH({RESP_FW})")
        w(f"    ) c{i}_adap (")
        w(f"        .clk(clk), .reset(reset),")
        w(f"        .bus_req(c{i}_bus_req), .bus_addr(c{i}_bus_addr), .bus_write_data(c{i}_bus_write_data),")
        w(f"        .bus_mem_write(c{i}_bus_mem_write), .bus_mem_size(c{i}_bus_mem_size), .bus_mem_unsigned(c{i}_bus_mem_unsigned),")
        w(f"        .bus_grant(c{i}_bus_grant), .bus_read_data(c{i}_bus_read_data),")
        w(f"        .req_out_valid(c{i}_req_out_valid), .req_out_flit(c{i}_req_out_flit), .req_out_ready(c{i}_req_out_ready),")
        w(f"        .resp_in_valid(c{i}_resp_in_valid), .resp_in_flit(c{i}_resp_in_flit), .resp_in_ready(c{i}_resp_in_ready)")
        w(f"    );")
        w("")

    w("    noc_mem_adapter #(")
    w(f"        .COORD_BITS({COORD_BITS}), .MEM_BYTES(SHARED_MEM_BYTES), .REQ_FLIT_WIDTH({REQ_FW}), .RESP_FLIT_WIDTH({RESP_FW})")
    w("    ) mem_adap (")
    w("        .clk(clk), .reset(reset),")
    w("        .req_in_valid(mem_req_in_valid), .req_in_flit(mem_req_in_flit), .req_in_ready(mem_req_in_ready),")
    w("        .resp_out_valid(mem_resp_out_valid), .resp_out_flit(mem_resp_out_flit), .resp_out_ready(mem_resp_out_ready)")
    w("    );")
    w("")

    # all_halted - ONE term per line, not one giant physical line - a
    # single joined line at large N overflows Icarus's lexer buffer
    # ("input buffer overflow, can't enlarge buffer because scanner uses
    # REJECT"), a real hard toolchain limit hit around ~3000+ cores.
    w("    assign all_halted =")
    for i in range(n_cores):
        sep = "&&" if i < n_cores - 1 else ";"
        w(f"        c{i}_halted {sep}")
    w("endmodule")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"wrote {OUT_PATH}: {n_cores} cores + 1 memory at ({MEM_X},{MEM_Y},{MEM_Z}), COORD_BITS={COORD_BITS}, REQ_FW={REQ_FW}, RESP_FW={RESP_FW}")


if __name__ == "__main__":
    main()
