"""Generator for AxISA's tb/tb_soc.v (the multi-core mesh test). Must
be regenerated at the same X/Y/Z size as tools/gen_soc_top.py's own
output, since it declares one wire pair and one soc_top port
connection per core.

Usage: python gen_tb_soc.py <X> <Y> <Z> <out_path>
       (defaults to 12 12 24 tb/tb_soc.v with no arguments)

c0 (shared_consumer.hex) busy-waits then reads c1's
(shared_producer.hex) payload through the arbitrated NoC - the
result (127) can only be correct if it genuinely observed the OTHER
core's write, not just "all cores ran without crashing" (that weaker
claim is what every other core, running independently on test1.hex,
proves happens concurrently and correctly alongside the real
cross-core traffic).

Per-core declarations and per-core soc_top port connections are each
written ONE PER LINE, not joined onto a single comma-separated
physical line - at large core counts (~3000+), a single giant joined
line overflows Icarus's lexer input buffer ("input buffer overflow,
can't enlarge buffer because scanner uses REJECT"), a real hard
toolchain limit distinct from any OOM/resource-exhaustion failure.
The failure-report display string near the end is deliberately NOT a
per-core %b dump for the same reason - a single string literal can't
be broken across lines the way a comma list can, so it only ever
reports c0/c1 (the two cores whose halted state actually gates this
test's pass/fail signal); a real per-core breakdown belongs in a
$dumpvars waveform, not a display string sized to the mesh.
"""
import sys

if len(sys.argv) >= 5:
    X_SIZE, Y_SIZE, Z_SIZE = int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3])
    OUT_PATH = sys.argv[4]
else:
    X_SIZE, Y_SIZE, Z_SIZE = 12, 12, 24
    OUT_PATH = "tb/tb_soc.v"
N_CORES = X_SIZE * Y_SIZE * Z_SIZE - 1  # one grid position is memory, not a core
labels = [f"c{i}" for i in range(N_CORES)]

defaults = {"c0": "sw/shared_consumer.hex", "c1": "sw/shared_producer.hex"}
for l in labels[2:]:
    defaults[l] = "sw/test1.hex"

expect = {"c0": 127, "c1": 77}
for l in labels[2:]:
    expect[l] = 200

lines = []
w = lines.append

w(f"// AxISA multi-core test: {N_CORES} real cpu_core.v instances in the 3D {X_SIZE}x{Y_SIZE}x{Z_SIZE} mesh")
w("// (rtl/soc_top.v) at once. Generated by tools/gen_tb_soc.py - do not")
w("// hand-edit; re-run the generator (at the same size as")
w("// tools/gen_soc_top.py's own soc_top.v) instead. c0")
w("// (shared_consumer.hex) busy-waits then reads c1's (shared_producer.hex)")
w("// payload through the arbitrated NoC - the result (127) can only be")
w("// correct if it genuinely observed the OTHER core's write, not just")
w(f"// \"all cores ran without crashing\" (that weaker claim is what c2-c{N_CORES-1},")
w("// running completely independently on test1.hex, prove happens")
w("// concurrently and correctly alongside the real cross-core traffic).")
w("`timescale 1ns/1ps")
w("")
for label in labels:
    up = label.upper()
    w(f"`ifndef {up}_INSTR_HEX")
    w(f'`define {up}_INSTR_HEX "{defaults[label]}"')
    w("`endif")
w("")
w("module tb_soc;")
w("    reg clk, reset;")
w("    wire all_halted;")
for label in labels:
    w(f"    wire {label}_halted;")
    w(f"    wire [31:0] {label}_tohost;")
w("")
for label in labels:
    w(f"    integer expect_{label};")
w("    integer max_cycles;")
w("    integer cycle_count;")
w("    integer any_fail;")
w("")
w("    soc_top #(")
w("        .INSTR_MEM_WORDS(1024), .DATA_MEM_WORDS(1024),")
for i, label in enumerate(labels):
    comma = "," if i < len(labels) - 1 else ""
    w(f"        .{label.upper()}_INSTR_HEX(`{label.upper()}_INSTR_HEX){comma}")
w("    ) dut (")
w("        .clk(clk), .reset(reset),")
for label in labels:
    w(f"        .{label}_halted({label}_halted), .{label}_tohost({label}_tohost),")
w("        .all_halted(all_halted)")
w("    );")
w("")
w("    always #5 clk = ~clk;")
w("")
w("    task check_core(input [31:0] got, input [31:0] expected, input [24*8-1:0] name);")
w("        begin")
w('            $display("%0s: tohost=%0d (0x%h)", name, got, got);')
w("            if (got === expected) begin")
w('                $display("PASS: %0s matches expected value %0d", name, expected);')
w("            end else begin")
w('                $display("FAIL: %0s tohost=%0d, expected=%0d", name, got, expected);')
w("                any_fail = 1;")
w("            end")
w("        end")
w("    endtask")
w("")
w("    initial begin")
for label in labels:
    up = label.upper()
    w(f'        if (!$value$plusargs("EXPECT_{up}_TOHOST=%d", expect_{label})) expect_{label} = {expect[label]};')
w('        if (!$value$plusargs("MAX_CYCLES=%d", max_cycles)) max_cycles = 200;')
w("")
w("        clk = 0;")
w("        reset = 1;")
w("        cycle_count = 0;")
w("        any_fail = 0;")
w("        @(posedge clk); @(posedge clk);")
w("        reset = 0;")
w("")
w("        while (!all_halted && cycle_count < max_cycles) begin")
w("            @(posedge clk);")
w("            cycle_count = cycle_count + 1;")
w("        end")
w("")
w("        if (!all_halted) begin")
w('            $display("FAIL: not all %0d cores halted within %0d cycles (c0=%b c1=%b)",')
w(f"                      {N_CORES}, max_cycles, c0_halted, c1_halted);")
w("            any_fail = 1;")
w("        end else begin")
w(f'            $display("All {N_CORES} cores halted after %0d cycles.", cycle_count);')
for label in labels:
    kind = "consumer" if label == "c0" else ("producer" if label == "c1" else "indep")
    w(f'            check_core({label}_tohost, expect_{label}, "{label}-core ({kind})");')
w(f'            if (!any_fail) $display("PASS: cross-core communication verified (c0 read c1' + "'" + 's write)");')
w("        end")
w("")
w("        $finish;")
w("    end")
w("endmodule")

with open(OUT_PATH, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"wrote {OUT_PATH}: {N_CORES} cores")
